### ISSUE TITLE
Feature Template

### ISSUE THREAD

**Issue by jfues** [jfues/PracticeInClass6#1]
Product Backlog
### Task
- [ ] Task 1 Modify index.html to include an empty content container #1
- [ ] Task 2 Update myscripts.js to load content dynamically without full page reloads#2 
- [ ] Task 3 Update directory structure to include content directory for articles#3
